image: "map_parking.png"
resolution: 1           #地图的分辨率：像素/米
origin: [0.0, 0.0, 0.0]   #初始点位置：在地图上的坐标以及航偏。航偏是指角度。
occupied_thresh: 0.1   #当像素占据的概率大于 0.65时候认为是完全占据的。
free_thresh: 0.05      #当像素占据概率小于0.196的时候，认为完全是空的
negate: 0
